# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dabda3a5d8ee161f8d7112665bd9375b707fd26bc4eb0c975f5325aaba5b725259f5979fac9a03ddcd39b13f2b066495ba25f365fd941be3d83f9ba388574ce4

test:
  secret_key_base: 912911dc7345e3fcbf7f17a0b08b1dee9a2f0d18cf272a89d15e875a9e96f664dc14439655258b8b7d59a980347143af3b19a905309ffd79984246e61e448547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
